### ISSUE TITLE
TypeError: dumpkvs() got an unexpected keyword argument 'step'

### ISSUE THREAD

**Issue by white-bubbleee** [polixir/RLAssistant#51]
Hi, I was running into an error in my own pytorch conda space testing the provided example sb3_ppo_example,

Traceback (most recent call last):
  File "E:\PycharmProject\My23Graduate_one\sb3_ppo_example\ppo\main.py", line 39, in <module>
    model.learn(total_timesteps=args.total_timesteps)
  File "E:\My_Envs\My23Graduate_env_one\lib\site-packages\stable_baselines3\ppo\ppo.py", line 308, in learn
    return super().learn(
  File "E:\My_Envs\My23Graduate_env_one\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 279, in learn
    self.logger.dump(step=self.num_timesteps)
TypeError: dumpkvs() got an unexpected keyword argument 'step'

And I tried to change the code like this, but it didn't work.

model.learn(total_timesteps=args.total_timesteps)=====>model.learn(total_timesteps=10000)

I don't know how to solve this problem. Is it caused by the excessively high version of stable-baselines3? I hope someone can help me solve it.

**Comment by Bai-Er** [comment]
stable-baselines3  is 2.1.0, gym is 0.26.2, cuda is 11.6

**Comment by Bai-Er** [comment]
I tried to use stable-baselines3 version 1.7.0, but the error was the same

**Comment by xionghuichen** [comment]
Hi, It is not the version issue. I found your model learning function locates the stable_baselines3 package, which cannot be compatible with RLA directly.  But you can just rewrite the learn function in "...\stable_baselines3\ppo\ppo.py", line 308 or the dump function in  stable_baselines3\common\on_policy_algorithm.py", line 279 to support RLA:
original code:
```
self.logger.dump(step=self.num_timesteps)
```
new code:
```
  # [RLA] set timesteps
  time_step_holder.set_time(self.num_timesteps)
  self.logger.dump()
```

This is also what we have done in the example code, plz see the following code for details: https://github.com/polixir/RLAssistant/blob/8191866db3272017d2cf41338ffa567b8f7421ad/example/sb3_ppo_example/ppo/ppo.py#L291-L367


In RLA, we create a global object "time_step_holder" to maintain the timestep, which can be set and get at any place in your project.

**Comment by white-bubbleee** [comment]
Thank you! Changing stable_baselines3\common\on_policy_algorithm.py", line 279 did solve my problem. Actually, there was a problem with using the entire code of sb3_ppo_example directly. This led me to switch to stable-baselines3 ppo earlier.

Traceback (most recent call last):
File "E:\PycharmProject\My23Graduate_one\sb3_ppo_example\ppo\main.py", line 32, in &lt; module&gt;
model = PPO(args.policy_type, env, verbose=1, seed=args.seed)
File "E:\PycharmProject\My23Graduate_one\sb3_ppo_example\ppo\ppo.py", line 96, in __init__
super(PPO, self).__init__(
File "E:\My_Envs\My23Graduate_env_one\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 81,  in __init__
super().__init__(
File "E:\My_Envs\My23Graduate_env_one\lib\site-packages\stable_baselines3\common\base_class.py", line 123, in __init__
self.policy_class = self._get_policy_from_name(policy)
File "E:\My_Envs\My23Graduate_env_one\lib\site-packages\stable_baselines3\common\base_class.py", line 338,  in _get_policy_from_name
raise ValueError(f"Policy {policy_name} unknown")
ValueError: Policy MlpPolicy unknown

After comparing the stable-baselines3 ppo.py, I added the following code to the PPO class of the sb3_ppo_example po.py file, in line 67:

policy_aliases: ClassVar[Dict[str, Type[BasePolicy]]] = {
"MlpPolicy": ActorCriticPolicy,
"CnnPolicy": ActorCriticCnnPolicy,
"MultiInputPolicy": MultiInputActorCriticPolicy,
}

I don't know if this change is appropriate, but it does fix the problem.

**Comment by xionghuichen** [comment]
Thanks for the reminder. It might be because the ppo.py we used is an older-version stable_baselines3. I will fix that recently. :)

**Comment by xionghuichen** [comment]
I have updated the example code here https://github.com/polixir/RLAssistant/pull/53/commits/b0e2da4f99a2d04c2488d8ff5b37d2b7672971d2
